global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'yougene-api'
    static_configs:
      - targets: ['${API_URL}']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    honor_labels: true
    scheme: https 