[build]
builder = "nixpacks"
nixpacksConfig = { node_version = "18" }
setup = ["npm install -g pnpm@latest"]
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 