[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install && pnpm build"

[deploy]
startCommand = "npm install -g pnpm && pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 