[build]
builder = "nixpacks"
nixpacksConfig = { node_version = "18" }
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "cd /app && node --experimental-specifier-resolution=node dist/src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
autoDeploy = false 